global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      aliasHeadersStrategy: delete
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: delete
  metrics:
    address: ":8082"
    http:
      aliasHeadersStrategy: delete

certificatesResolvers:
  cloudflare:
    acme:
      email: ${TRAEFIK_ACME_EMAIL:?}
      storage: /etc/traefik/certs/acme.json
      dnsChallenge:
        provider: cloudflare

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
    watch: true
  file:
    directory: /etc/traefik/conf
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
